import { Nunito_Sans } from "next/font/google";
import 'remixicon/fonts/remixicon.css'
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { Toaster } from "react-hot-toast";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
         <Toaster position="top-right" />
        <ReduxProvider>
          {children}
        </ReduxProvider></body>
    </html>
  );
}
